SchoolErp/Controllers/Teacher/TeacherDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolErp.Config;
using SchoolErp.Models.Admin;
using System.Data.SqlClient;
using System.Data;
namespace SchoolErp.Controllers.Teacher
{
    public class TeacherDashboardController : Controller
    {
        // GET: TeacherDashboard
        public ActionResult Index(int PageNumber = 1)
        {
            string Username = (string)Session["Username"];
            List<Student> student = new List<Student>();
            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("GetAssignedStudent", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@Username", Username);
                    if (con.State != System.Data.ConnectionState.Open)

                        con.Open();

                    SqlDataReader sdr = cmd.ExecuteReader();

                    DataTable dtTable = new DataTable();

                    dtTable.Load(sdr);

                    foreach (DataRow row in dtTable.Rows)
                    {
                        student.Add(
                            new Student
                            {
                                AdmissionNo = Convert.ToInt32(row["AdmissionNo"].ToString()),
                                StudentName = row["FullName"].ToString(),
                                ClassLevel = row["ClassLevel"].ToString(),
                                ClassAphabet = row["ClassAlphabet"].ToString(),
                                Gender = row["Gender"].ToString()

                            }

                            );
                    }
                }
            }
            ViewBag.TotalPages = Math.Ceiling(student.Count() / 10.0);
            ViewBag.PageNumber = PageNumber;
            student = student.Skip((PageNumber - 1) * 10).Take(10).ToList();
            return View(student);
        }


        [HttpPost]
        public ActionResult Index(string searchtxt)
        {
            string Username = (string)Session["Username"];
            List<Student> student = new List<Student>();
            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("SearchAssignedStudent", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;

                    cmd.Parameters.AddWithValue("@Studentname", searchtxt);
                    cmd.Parameters.AddWithValue("@Username", Username);
                    if (con.State != System.Data.ConnectionState.Open)

                        con.Open();

                    SqlDataReader sdr = cmd.ExecuteReader();

                    DataTable dtTable = new DataTable();

                    dtTable.Load(sdr);

                    foreach (DataRow row in dtTable.Rows)
                    {
                        student.Add(
                            new Student
                            {
                                AdmissionNo = Convert.ToInt32(row["AdmissionNo"].ToString()),
                                StudentName = row["FullName"].ToString(),
                                ClassLevel = row["ClassLevel"].ToString(),
                                ClassAphabet = row["ClassAlphabet"].ToString(),
                                Gender = row["Gender"].ToString()

                            }

                            );
                    }
                }
            }
            ViewBag.TotalPages = Math.Ceiling(student.Count() / 10.0);
            return View(student);

        }
            }
        }
       


    

SchoolErp/Views/TeacherDashboard/Index.cshtml
@model IEnumerable<SchoolErp.Models.Admin.Student>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Teacher.cshtml";
}


<div class="page-wrapper">


    <style>
        .pagination {
            display: inline-block;
        }

            .pagination a {
                color: black;
                float: left;
                padding: 8px 16px;
                text-decoration: none;
            }

                .pagination a.active {
                    background-color: #4CAF50;
                    color: white;
                }

                .pagination a:hover:not(.active) {
                    background-color: #ddd;
                }
    </style>

    <div class="page-breadcrumb">



        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Dashboard</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page"> Dashboard</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <div class="row">
            <!-- Column -->
            <div class="col-md-6 col-lg-3">
                <div class="card card-hover">
                    <div class="box bg-cyan text-center">
                        <h1 class="font-light text-white"><i class="fas fa-users"></i></h1>
                        <h6 class="text-white">Staff</h6>
                    </div>
                </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-3">
                <div class="card card-hover">
                    <div class="box bg-success text-center">
                        <h1 class="font-light text-white"><i class="fas fa-user-graduate"></i></h1>
                        <h6 class="text-white">Student</h6>
                    </div>
                </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-3">
                <div class="card card-hover">
                    <div class="box bg-warning text-center">
                        <h1 class="font-light text-white"><i class="fas fa-book"></i></h1>
                        <h6 class="text-white">Subject</h6>
                    </div>
                </div>
            </div>
            <!-- Column -->
            <div class="col-md-6 col-lg-3">
                <div class="card card-hover">
                    <div class="box bg-danger text-center">
                        <h1 class="font-light text-white"><i class="fas fa-level-up-alt"></i></h1>
                        <h6 class="text-white">Class</h6>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title m-b-0"><i class="fas fa-users"></i> Student</h5>
                    </div>


                    <div class="row">
                        <div class="card-body">
                            

                            @using (Html.BeginForm("Index", "TeacherDashboard", FormMethod.Post))
                            {
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Student Name</label>
                                            @Html.TextBox("searchtxt", null, new { @class = "form-control", @placeholder = "Search Student" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn btn-dark">
                                                <i class="fas fa-search"></i>  Query Table
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            }

                            <table class="table">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.AdmissionNo)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.StudentName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Gender)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ClassLevel)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ClassAphabet)
                                        </th>

                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AdmissionNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StudentName)
                                        </td>
                                       
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Gender)
                                        </td>
                             
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ClassLevel)
                                        </td>
                                        
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ClassAphabet)
                                        </td>
                                       
                                    </tr>
                                }

                            </table>
                            



                            @{
                                double totalPages = ViewBag.TotalPages;

                                <ul class="pagination">
                                    @if (ViewBag.PageNumber == 1)
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Previous", "Index", new { PageNumber = ViewBag.PageNumber })
                                        </li>
                                    }
                                    else
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Previous", "Index", new { PageNumber = ViewBag.PageNumber - 1 })
                                        </li>
                                    }
                                    @for (int i = 1; i <= totalPages; i++)
                                    {
                                        if (i == ViewBag.PageNumber)
                                        {
                                            <li class="active" style="float:left">
                                                @Html.ActionLink(i.ToString(), "Index", new { PageNumber = i })
                                            </li>
                                        }
                                        else
                                        {
                                            <li class="active" style="float:left">
                                                @Html.ActionLink(i.ToString(), "Index", new { PageNumber = i })
                                            </li>
                                        }
                                    }
                                    @if (ViewBag.PageNumber == totalPages)
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Next", "Index", new { PageNumber = ViewBag.PageNumber })
                                        </li>
                                    }
                                    else
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Next", "Index", new { PageNumber = ViewBag.PageNumber + 1 })
                                        </li>
                                    }
                                </ul>
                            }




                        </div>
                    </div>

                </div>


            </div>

        </div>
    </div>


</div>