SchoolErp/Models/Teacher/StudentAttendance.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SchoolErp.Models.Teacher
{
    public class StudentAttendance
    {
        public int AdmissionNo { get; set; }

        public string Studentname { get; set; }

        public DateTime Date { get; set; }

        public string Remark { get; set; }

        
    }
}

SchoolErp/Controllers/Teacher/TeacherClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolErp.Config;
using SchoolErp.Models.Teacher;
using SchoolErp.Models.Admin;
using System.Data.SqlClient;
using System.Data;

namespace SchoolErp.Controllers.Teacher
{
    public class TeacherClassController : Controller
    {
        // GET: TeacherClass
        public ActionResult StudentAttendance(int PageNumber = 1)
        {
            string Username = (string)Session["Username"];
            List<StudentAttendance> student = new List<StudentAttendance>();
            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("GetStudentAttendance", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@Username", Username);
                    if (con.State != System.Data.ConnectionState.Open)

                        con.Open();

                    SqlDataReader sdr = cmd.ExecuteReader();

                    DataTable dtTable = new DataTable();

                    dtTable.Load(sdr);

                    foreach (DataRow row in dtTable.Rows)
                    {
                        student.Add(
                            new StudentAttendance
                            {
                                AdmissionNo = Convert.ToInt32(row["AdmissionNo"].ToString()),
                                Studentname = row["FullName"].ToString(),
                                Date = Convert.ToDateTime(row["Date"].ToString()),
                                Remark = row["Remark"].ToString()


                            }

                            );
                    }
                }
            }
            ViewBag.TotalPages = Math.Ceiling(student.Count() / 10.0);
            ViewBag.PageNumber = PageNumber;
            student = student.Skip((PageNumber - 1) * 10).Take(10).ToList();
            return View(student);
        }
       
        public ActionResult MarkAttendance()
        {
            FillName();
            return View();
        }

        public void FillName()
        {
            string Username = (string)Session["Username"];
            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("Select s.AdmissionNo, s.FullName  from Student s inner join AssignClass a on a.ClassLevelID = s.ClassLevelID inner join RoleTbl r on r.StaffID = a.StaffID where r.Username = '" + Username + "'", con))
                {
                    cmd.Parameters.AddWithValue("Username", Session["Username"].ToString());
                    if (con.State != System.Data.ConnectionState.Open)
                        con.Open();
                    SqlDataReader rdr = cmd.ExecuteReader();
                    List<SelectListItem> li = new List<SelectListItem>();
                    li.Add(new SelectListItem { Text = "Select" , Value = "0" });
                    while(rdr.Read())
                    {
                        li.Add(new SelectListItem { Text = rdr[1].ToString(),Value = rdr[0].ToString() });
                    }

                    ViewData["Id"] = li;
                }
            }
        }

        [HttpPost]
        public ActionResult MarkAttendance(StudentAttendance student)
        {
            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("InserStudentAttendance", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@AddmissionNo", student.AdmissionNo);
                    cmd.Parameters.AddWithValue("@Date", student.Date);
                    cmd.Parameters.AddWithValue("@Remark", student.Remark);

                    if (con.State != System.Data.ConnectionState.Open)

                        con.Open();
                    cmd.ExecuteNonQuery();
                }

                con.Close();
            }

            TempData["SuccessMessage"] = "Record Saved Successfully";
            return RedirectToAction("StudentAttendance");
        }
      
        public ActionResult StudentList(int PageNumber = 1)
        {
            List<Student> student = new List<Student>();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("GetStudentList", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    if (con.State != System.Data.ConnectionState.Open)

                        con.Open();

                    SqlDataReader sdr = cmd.ExecuteReader();

                    DataTable dtSessions = new DataTable();

                    dtSessions.Load(sdr);

                    foreach (DataRow row in dtSessions.Rows)
                    {
                        student.Add(
                            new Student
                            {
                                AdmissionNo = Convert.ToInt32(row["AdmissionNo"].ToString()),
                                StudentName = row["FullName"].ToString(),
                                SessionName = row["Session"].ToString(),
                                ClassLevel = row["ClassLevel"].ToString(),
                                ClassAphabet = row["ClassAlphabet"].ToString(),
                                Gender = row["Gender"].ToString()


                            }

                            );
                    }
                }

              


            }

            ViewBag.TotalPages = Math.Ceiling(student.Count() / 10.0);
            ViewBag.PageNumber = PageNumber;
            student = student.Skip((PageNumber - 1) * 10).Take(10).ToList();
            return View(student);

        }
        [HttpPost]
        public ActionResult StudentList(string searchtxt)
        {
            List<Student> student = new List<Student>();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("SearchStudent", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@Studentname", searchtxt);
                    if (con.State != System.Data.ConnectionState.Open)

                        con.Open();

                    SqlDataReader sdr = cmd.ExecuteReader();

                    DataTable dtSessions = new DataTable();

                    dtSessions.Load(sdr);

                    foreach (DataRow row in dtSessions.Rows)
                    {
                        student.Add(
                            new Student
                            {
                                AdmissionNo = Convert.ToInt32(row["AdmissionNo"].ToString()),
                                StudentName = row["FullName"].ToString(),
                                SessionName = row["Session"].ToString(),
                                ClassLevel = row["ClassLevel"].ToString(),
                                ClassAphabet = row["ClassAlphabet"].ToString(),
                                Gender = row["Gender"].ToString()


                            }

                            );
                    }
                }




            }

            ViewBag.TotalPages = Math.Ceiling(student.Count() / 10.0);
            return View(student);
        }

        private static List<Subject> PopulateSubject()
        {
            List<Subject> subject = new List<Subject>();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {

                using (SqlCommand cmd = new SqlCommand("select  * from Subject ", con))
                {
                    cmd.Connection = con;

                    con.Open();

                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            subject.Add(
                                new Subject
                                {
                                    SubjectID = Convert.ToInt32(sdr["ID"]),
                                    Subjectname = sdr["Subject"].ToString()
                                }

                                );
                        }
                        con.Close();
                    }


                }

                return subject;

            }
        }

        private static List<Session> PopulateSession()
        {
            List<Session> session = new List<Session>();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {

                using (SqlCommand cmd = new SqlCommand("Select ID, Session + '  ' + Term as Name from SessionTble where IsActive = 'Active' ", con))
                {
                    cmd.Connection = con;

                    con.Open();

                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            session.Add(
                                new Session
                                {
                                    SessionID = Convert.ToInt32(sdr["ID"]),
                                    SessionName = sdr["Name"].ToString()
                                }

                                );
                        }
                        con.Close();
                    }


                }

                return session;

            }
        }

        public ActionResult AssignMark(int id)
        {

SchoolErp/Views/TeacherClass/StudentAttendance.cshtml
@model IEnumerable<SchoolErp.Models.Teacher.StudentAttendance>

@{
    ViewBag.Title = "StudentAttendance";
    Layout = "~/Views/Shared/Teacher.cshtml";
}

<div class="page-wrapper">


    <style>
        .pagination {
            display: inline-block;
        }

            .pagination a {
                color: black;
                float: left;
                padding: 8px 16px;
                text-decoration: none;
            }

                .pagination a.active {
                    background-color: #4CAF50;
                    color: white;
                }

                .pagination a:hover:not(.active) {
                    background-color: #ddd;
                }
    </style>

    <div class="page-breadcrumb">

        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Student Attendance</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page"> Student Attendance</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">

            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title m-b-0"><i class="fas fa-users"></i> Student Attendance</h5>
                    </div>


                    <div class="row">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <a href="@Url.Action("MarkAttendance", "TeacherClass")" class="btn btn btn-dark">
                                            <i class="fas fa-plus-square"></i>
                                            <span>
                                                <strong>Mark Attendance</strong>
                                            </span>
                                        </a>
                                    </div>
                                </div>

                            </div>

                            @using (Html.BeginForm("Student", "Student", FormMethod.Post))
                            {
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Student Name</label>
                                            @Html.TextBox("searchtxt", null, new { @class = "form-control", @placeholder = "Student Name" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn btn-dark">
                                                <i class="fas fa-search"></i>  Query Table
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            }


                            <table class="table">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.AdmissionNo)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Studentname)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Date)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Remark)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AdmissionNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Studentname)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Date)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Remark)
                                        </td>
                                        <td>
                                            <a href="@Url.Action("EditStudentAttendance", "Student", new { id = item.AdmissionNo })" class="btn btn-mini btn-outkine-orange icon-edit bigger-10"><img src="~/assets/48763_file_edit_icon.png" /></a>
                                        </td>
                                    </tr>
                                }

                            </table>



                            @{
                                double totalPages = ViewBag.TotalPages;

                                <ul class="pagination">
                                    @if (ViewBag.PageNumber == 1)
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Previous", "StudentAttendance", new { PageNumber = ViewBag.PageNumber })
                                        </li>
                                    }
                                    else
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Previous", "StudentAttendance", new { PageNumber = ViewBag.PageNumber - 1 })
                                        </li>
                                    }
                                    @for (int i = 1; i <= totalPages; i++)
                                    {
                                        if (i == ViewBag.PageNumber)
                                        {
                                            <li class="active" style="float:left">
                                                @Html.ActionLink(i.ToString(), "StudentAttendance", new { PageNumber = i })
                                            </li>
                                        }
                                        else
                                        {
                                            <li class="active" style="float:left">
                                                @Html.ActionLink(i.ToString(), "StudentAttendance", new { PageNumber = i })
                                            </li>
                                        }
                                    }
                                    @if (ViewBag.PageNumber == totalPages)
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Next", "StudentAttendance", new { PageNumber = ViewBag.PageNumber })
                                        </li>
                                    }
                                    else
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Next", "StudentAttendance", new { PageNumber = ViewBag.PageNumber + 1 })
                                        </li>
                                    }
                                </ul>
                            }




                        </div>
                    </div>

                </div>


            </div>

        </div>
    </div>


</div>



@section Scripts
{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
        });
    </script>
    }

SchoolErp/Views/TeacherClass/StudentList.cshtml
@model IEnumerable<SchoolErp.Models.Admin.Student>

@{
    ViewBag.Title = "StudentList";
    Layout = "~/Views/Shared/Teacher.cshtml";
}


<div class="page-wrapper">


    <style>
        .pagination {
            display: inline-block;
        }

            .pagination a {
                color: black;
                float: left;
                padding: 8px 16px;
                text-decoration: none;
            }

                .pagination a.active {
                    background-color: #4CAF50;
                    color: white;
                }

                .pagination a:hover:not(.active) {
                    background-color: #ddd;
                }
    </style>

    <div class="page-breadcrumb">

        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Student</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page"> Student</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">

            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title m-b-0"><i class="fas fa-users"></i> Student</h5>
                    </div>


                    <div class="row">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <a href="@Url.Action("CreateStudent", "Student")" class="btn btn btn-dark">
                                            <i class="fas fa-plus-square"></i>
                                            <span>
                                                <strong>Create</strong>
                                            </span>
                                        </a>
                                    </div>
                                </div>

                            </div>

                            @using (Html.BeginForm("StudentList", "TeacherClass", FormMethod.Post))
                            {
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Student Name</label>
                                            @Html.TextBox("searchtxt", null, new { @class = "form-control", @placeholder = "Student Name" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn btn-dark">
                                                <i class="fas fa-search"></i>  Query Table
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            }



                            <table class="table">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.AdmissionNo)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.StudentName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Gender)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AdmissionNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StudentName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Gender)
                                        </td>                                     
                                        <td>
                                            <a href="@Url.Action("AssignMark", "TeacherClass", new { id = item.AdmissionNo })" class="btn btn-mini btn-outkine-orange icon-edit bigger-10"><img src="~/assets/48810_user_add_icon.png" /></a>
                                        </td>
                                    </tr>
                                }

                            </table>


                            @{
                                double totalPages = ViewBag.TotalPages;

                                <ul class="pagination">
                                    @if (ViewBag.PageNumber == 1)
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Previous", "StudentList", new { PageNumber = ViewBag.PageNumber })
                                        </li>
                                    }
                                    else
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Previous", "StudentList", new { PageNumber = ViewBag.PageNumber - 1 })
                                        </li>
                                    }
                                    @for (int i = 1; i <= totalPages; i++)
                                    {
                                        if (i == ViewBag.PageNumber)
                                        {
                                            <li class="active" style="float:left">
                                                @Html.ActionLink(i.ToString(), "StudentList", new { PageNumber = i })
                                            </li>
                                        }
                                        else
                                        {
                                            <li class="active" style="float:left">
                                                @Html.ActionLink(i.ToString(), "StudentList", new { PageNumber = i })
                                            </li>
                                        }
                                    }
                                    @if (ViewBag.PageNumber == totalPages)
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Next", "StudentList", new { PageNumber = ViewBag.PageNumber })
                                        </li>
                                    }
                                    else
                                    {
                                        <li class="active" style="float:left">
                                            @Html.ActionLink("Next", "StudentList", new { PageNumber = ViewBag.PageNumber + 1 })
                                        </li>
                                    }
                                </ul>
                            }






                        </div>
                    </div>

                </div>


            </div>

        </div>
    </div>


</div>


@section Scripts
{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
        });
        @*function Delete(id) {
            alertify.confirm('Web Api CRUD Operations','Are You Sure to Delete this Record ?',function(){
                window.location.href  = '@Url.Action("Delete","Employee")/'+id;
            },null );
        }*@
    </script>


}