SchoolErp/Models/Admin/CollectFee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SchoolErp.Models.Admin
{
    public class CollectFee
    {
        public int Id { get; set; }

        public int AdmissionNo { get; set; }

        public string StudentName { get; set; }

        public int ClassLevelID { get; set; }

        public string ClassLevelname { get; set; }

        public string Session { get; set; }

        public decimal Amount { get; set; }

        public string TellerNo { get; set; }

        public string Bank { get; set; }

        public DateTime Date { get; set; }

        
    }


}

SchoolErp/Models/Admin/FeeType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SchoolErp.Models.Admin
{
    public class FeeType
    {
        public int FeeTypeID { get; set; }

        public string FeeName { get; set; }
    }
}

SchoolErp/Controllers/Admin/FeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolErp.Config;
using SchoolErp.Models.Admin;
using System.Data.SqlClient;
using System.Data;
namespace SchoolErp.Controllers.Admin
{
    public class FeeController : Controller
    {
        // GET: Fee
        public ActionResult CollectedFee()
        {
            List<CollectFee> fee = new List<CollectFee>();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("getCollectedFee", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    if (con.State != System.Data.ConnectionState.Open)

                        con.Open();

                    SqlDataReader sdr = cmd.ExecuteReader();

                    DataTable dtTable = new DataTable();

                    dtTable.Load(sdr);

                    foreach (DataRow row in dtTable.Rows)
                    {
                        fee.Add(
                            new CollectFee
                            {
                                Id = Convert.ToInt32(row["ID"].ToString()),
                                AdmissionNo = Convert.ToInt32(row["AdmissionNo"].ToString()),
                                StudentName = row["FullName"].ToString(),
                                Session = row["Session"].ToString(),
                                Amount = Convert.ToInt32(row["Amount"].ToString()),
                                Bank = row["Bank"].ToString(),
                                TellerNo =row["Tellerno"].ToString()


                            }

                            );
                    }
                }
            }
            return View(fee);
        }

        public ActionResult StudentCollectFee()
        {
            List<Student> student = new List<Student>();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("GetStudentList", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    if (con.State != System.Data.ConnectionState.Open)

                        con.Open();

                    SqlDataReader sdr = cmd.ExecuteReader();

                    DataTable dtSessions = new DataTable();

                    dtSessions.Load(sdr);

                    foreach (DataRow row in dtSessions.Rows)
                    {
                        student.Add(
                            new Student
                            {
                                AdmissionNo = Convert.ToInt32(row["AdmissionNo"].ToString()),
                                StudentName = row["FullName"].ToString(),
                                ClassLevel = row["ClassLevel"].ToString(),
                                ClassAphabet = row["ClassAlphabet"].ToString(),
                                Gender = row["Gender"].ToString()


                            }

                            );
                    }
                }

               


            }

            
            return View(student);
        }

        public ActionResult CollectFees(int id)
        {

            ViewBag.Session = PopulateSession();

            CollectFee fee = new CollectFee();

            DataTable dtsession = new DataTable();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                con.Open();
                string query = "Select * from Student where AdmissionNo = @ID";
                SqlDataAdapter sqlDA = new SqlDataAdapter(query, con);
                sqlDA.SelectCommand.Parameters.AddWithValue("@ID", id);

                sqlDA.Fill(dtsession);

            }
            if (dtsession.Rows.Count == 1)
            {
                fee.AdmissionNo = Convert.ToInt32(dtsession.Rows[0][0].ToString());
                fee.StudentName = dtsession.Rows[0][1].ToString();
                fee.ClassLevelID = Convert.ToInt32(dtsession.Rows[0][8].ToString());
                return View(fee);
            }

            else


                return View("StudentCollectedFee");
        }

        [HttpPost]
        public ActionResult CollectFees(CollectFee fee)
        {
            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("InsertFeeDetails", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("AddmissionNo", fee.AdmissionNo);
                    cmd.Parameters.AddWithValue("@ClassLevelID", fee.ClassLevelID);
                    cmd.Parameters.AddWithValue("@Session", fee.Session);
                    cmd.Parameters.AddWithValue("@Amount", fee.Amount);
                    cmd.Parameters.AddWithValue("@TellerNo", fee.TellerNo);
                    cmd.Parameters.AddWithValue("@Bank", fee.Bank);
                    cmd.Parameters.AddWithValue("@Date", DateTime.Now);

                    if (con.State != System.Data.ConnectionState.Open)

                        con.Open();
                    cmd.ExecuteNonQuery();


                    con.Close();
                }

                TempData["SuccessMessage"] = "Record Saved Successfully";
                return RedirectToAction("CollectedFee");
            }
        }

        private static List<Session> PopulateSession()
        {
            List<Session> session = new List<Session>();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {

                using (SqlCommand cmd = new SqlCommand("select distinct Session from SessionTble", con))
                {
                    cmd.Connection = con;

                    con.Open();

                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            session.Add(
                                new Session
                                {
                                    //SessionID = Convert.ToInt32(sdr["ID"]),
                                    SessionName = sdr["Session"].ToString()
                                }

                                );
                        }
                        con.Close();
                    }


                }

                return session;

            }
        }

        public ActionResult PrintFeeReciept(int id)
        {

            CollectFee fee = new CollectFee();

            DataTable dtsession = new DataTable();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                con.Open();
                string query = "select * from FeePayment f inner join Student s on f.AdmissionNo = s.AdmissionNo inner join ClassLevel cl on f.ClassLevelID = cl.ID where f.ID = @ID";
                SqlDataAdapter sqlDA = new SqlDataAdapter(query, con);
                sqlDA.SelectCommand.Parameters.AddWithValue("@ID", id);

                sqlDA.Fill(dtsession);

            }
            if (dtsession.Rows.Count == 1)
            {
                fee.Id = Convert.ToInt32(dtsession.Rows[0][0].ToString());
                fee.AdmissionNo = Convert.ToInt32(dtsession.Rows[0][1].ToString());
                fee.StudentName = dtsession.Rows[0][9].ToString();
                fee.TellerNo = dtsession.Rows[0][5].ToString();
                fee.Amount = Convert.ToDecimal(dtsession.Rows[0][4].ToString());
                fee.ClassLevelname = dtsession.Rows[0][24].ToString();
                fee.Session = dtsession.Rows[0][3].ToString();
                return View(fee);
            }

            else


                return View("CollectedFee");

        }

    }
}

SchoolErp/Views/Fee/CollectFees.cshtml
@model SchoolErp.Models.Admin.CollectFee

@{
    ViewBag.Title = "CollectFees";
    Layout = "~/Views/Shared/Admin.cshtml";
}

<div class="page-wrapper">

    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Fee</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Fee</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>


    <div class="container-fluid">

        <div class="row">

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title m-b-0"><i class="fab fa-paypal"></i> Fee</h5>
                    </div>

                    <div class="row">
                        <div class=" card-body">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()


                                <div class="form-horizontal">
                                   
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    
                                            @Html.HiddenFor(model => model.AdmissionNo, new { htmlAttributes = new { @class = "form-control"  } })
                                           

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.StudentName, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control", disabled = "true" } })
                                            @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                   
                                     @Html.HiddenFor(model => model.ClassLevelID, new { htmlAttributes = new { @class = "form-control" } })
                                           

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Session, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.DropDownListFor(model => model.Session, new SelectList(ViewBag.Session, "SessionName", "SessionName"),  new { @class = "form-control" } )
                                            @Html.ValidationMessageFor(model => model.Session, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.TellerNo, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.TellerNo, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.TellerNo, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Bank, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            <select class="form-control" id="StudentGender" name="Bank">
                                                <option>Select Bank</option>
                                                <option>First Bank</option>
                                                <option>GTB Bank</option>
                                                <option>Zenith Bank</option>
                                            </select>
                                            @Html.ValidationMessageFor(model => model.Bank, "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Create" class="btn btn-default" />
                                        </div>
                                    </div>
                                </div>


                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>




<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SchoolErp/Views/Fee/CollectedFee.cshtml
@model IEnumerable<SchoolErp.Models.Admin.CollectFee>

@{
    ViewBag.Title = "CollectedFee";
    Layout = "~/Views/Shared/Admin.cshtml";
}

<div class="page-wrapper">

    <div class="page-breadcrumb">

        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Fee</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page"> Fee</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">

            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title m-b-0"><i class="fab fa-paypal"></i> Fee</h5>
                    </div>


                    <div class="row">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <a href="@Url.Action("StudentCollectFee","Fee")" class="btn btn btn-dark">
                                            <i class="fas fa-plus-square"></i>
                                            <span>
                                                <strong>Collect Fee</strong>
                                            </span>
                                        </a>
                                    </div>
                                </div>

                            </div>


                            <table class="table">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.AdmissionNo)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.StudentName)
                                        </th>

                                        <th>
                                            @Html.DisplayNameFor(model => model.Session)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Amount)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.TellerNo)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Bank)
                                        </th>

                                        <th></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AdmissionNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StudentName)
                                        </td>                                       
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Session)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Amount)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TellerNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Bank)
                                        </td>
                                        <td>
                                            <a href="@Url.Action("PrintFeeReciept","Fee", new { id = item.Id})" class="btn btn-mini btn-outkine-orange icon-edit bigger-10"><img src="~/assets/2620507_employee_job_print_seeker_unemployee_icon.png" /></a>
                                        </td>
                                    </tr>
                                }

                            </table>
                            

                        </div>
                    </div>

                </div>


            </div>

        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
        });
       
    </script>


}

SchoolErp/Views/Fee/PrintFeeReciept.cshtml
@model SchoolErp.Models.Admin.CollectFee

@{
    Layout = null;
}

<link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicon.png">
<title>Matrix Template - The Ultimate Multipurpose admin template</title>
<!-- Custom CSS -->
<link href="~/assets/libs/fullcalendar/dist/fullcalendar.min.css" rel="stylesheet" />
<link href="~/assets/extra-libs/calendar/calendar.css" rel="stylesheet" />
<link href="~/dist/css/style.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<div class="page-wrapper">
    <!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Container fluid  -->
<!-- ============================================================== -->

<div class="container-fluid">
    
    <div class="row">
        <div class="col-md-12">
            <div class="card card-body printableArea">
                <form name="GeneratePayrollSLip" method="post">
                    <h3><b>Reciept</b> <span class="pull-right"></span></h3>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="pull-left">
                                <address>
                                    <h3> &nbsp;<b class="text-danger">Matrix International School</b></h3>
                                    <p class="text-muted m-l-5">
                                        E 104, Dharti-2,
                                        <br /> Nr' Viswakarma Temple,
                                        <br /> Talaja Road,
                                        <br /> Bhavnagar - 364002
                                    </p>
                                </address>
                            </div>
                            <div class="pull-right text-right">
                                <address>
                                    <h3>To,</h3>
                                    <h4 class="font-bold">@Html.DisplayFor(model => model.StudentName)</h4>
                                    <h4 class="font-bold">Session:@Html.DisplayFor(model => model.Session)</h4>
                                    <h4 class="font-bold">Teller ID:@Html.DisplayFor(model => model.TellerNo)</h4>
                                    <h4 class="font-bold">Level:@Html.DisplayFor(model => model.ClassLevelname)</h4>
                                </address>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="table-responsive m-t-40" style="clear: both;">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th class="text-center">#</th>
                                            <th>Description</th>
                                            <th class="text-right">Amount</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="text-center">1</td>
                                            <td>School Fee</td>
                                            <td class="text-right">$@Html.DisplayFor(model => model.Amount)</td>
                                        </tr>
                                       
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        
                        <div class="col-md-12">
                            <div class="pull-right m-t-30 text-right">
                                <hr>
                                <h3><b>Total Pay :</b> $@Html.DisplayFor(model => model.Amount) </h3>
                            </div>
                            <div class="clearfix"></div>
                            <hr>
                            <div class="text-right">
                                <div class="text-right">

                                </div>
                            </div>
                        </div>                        
                   
                        </form>
            </div>
        </div>

    </div>
</div>

    

<script src="~/assets/libs/jquery/dist/jquery.min.js"></script>
<script src="~/dist/js/jquery.ui.touch-punch-improved.js"></script>
<script src="~/dist/js/jquery-ui.min.js"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="~/assets/libs/popper.js/dist/umd/popper.min.js"></script>
<script src="~/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- slimscrollbar scrollbar JavaScript -->
<script src="~/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
<script src="~/assets/extra-libs/sparkline/sparkline.js"></script>
<!--Wave Effects -->
<script src="~/dist/js/waves.js"></script>
<!--Menu sidebar -->
<script src="~/dist/js/sidebarmenu.js"></script>
<!--Custom JavaScript -->
<script src="~/dist/js/custom.min.js"></script>
<!-- this page js -->
<script src="~/assets/libs/moment/min/moment.min.js"></script>
<script src="~/assets/libs/fullcalendar/dist/fullcalendar.min.js"></script>
<script src="~/dist/js/pages/calendar/cal-init.js"></script>

SchoolErp/Views/Fee/StudentCollectFee.cshtml
@model IEnumerable<SchoolErp.Models.Admin.Student>

@{
    ViewBag.Title = "StudentCollectFee";
    Layout = "~/Views/Shared/Admin.cshtml";
}
<div class="page-wrapper">

    <div class="page-breadcrumb">

        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Fee</h4>
                <div class="ml-auto text-right">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page"> Fee</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">

            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title m-b-0"><i class="fab fa-paypal"></i> Fee</h5>
                    </div>


                    <div class="row">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                    </div>
                                </div>

                            </div>

                            <table class="table">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.AdmissionNo)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.StudentName)
                                        </th>

                                        <th>
                                            @Html.DisplayNameFor(model => model.Gender)
                                        </th>

                                        <th>
                                            @Html.DisplayNameFor(model => model.ClassLevel)
                                        </th>

                                        <th>
                                            @Html.DisplayNameFor(model => model.ClassAphabet)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AdmissionNo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StudentName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Gender)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ClassLevel)
                                        </td>
                                        
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ClassAphabet)
                                        </td>
                                        <td>
                                            <a href="@Url.Action("CollectFees","Fee", new { id = item.AdmissionNo})" class="btn btn-mini btn-outkine-orange icon-edit bigger-10"><img src="~/assets/48810_user_add_icon.png" /></a>
                                        </td>
                                    </tr>
                                }

                            </table>
                            


                        </div>
                    </div>

                </div>


            </div>

        </div>
    </div>
</div>